Repository TeamLumi/Luminescent_ExLaunch, pull requests merged in 2023-07, with the labels that each got.

#38 Port - Key items
  src/mod/data/incense_slots.h
  src/mod/data/items.h
  src/mod/externals/Audio/AudioInstance.h
  src/mod/externals/Audio/AudioManager.h
  src/mod/externals/ContextMenuID.h
  src/mod/externals/Dpr/Battle/Logic/BTL_CLIENT.h
  src/mod/externals/Dpr/Battle/Logic/CantEscapeCode.h
  src/mod/externals/Dpr/EvScript/EvCmdID.h
  src/mod/externals/Dpr/EvScript/EvDataManager.h
  src/mod/externals/Dpr/UI/PokemonPartyItem.h
  src/mod/externals/Dpr/UI/UIBag.h
  src/mod/externals/Dpr/UI/UIMsgWindowController.h
  src/mod/externals/Dpr/UI/UIWindow.h
  src/mod/externals/EvData/ArgType.h
  src/mod/externals/FlagWork_Enums.h
  src/mod/externals/GameController.h
  src/mod/externals/SmartPoint/AssetAssistant/SingletonMonoBehaviour.h
  src/mod/externals/System/Action.h
  src/mod/externals/System/Primitives.h
  src/mod/externals/UnityEngine/GameObject.h
  src/mod/externals/il2cpp-api.h
  src/mod/features/ability_changes.cpp
  src/mod/features/badge_check.cpp
  src/mod/features/key_items.cpp
  src/mod/features/key_items/clothing_trunk.cpp
  src/mod/features/key_items/incense_burner.cpp
  src/mod/features/key_items/infinite_repel.cpp
  src/mod/features/key_items/key_items.h
  src/mod/features/level_cap.cpp
  src/mod/features/main.cpp
  src/mod/features/more_settings.cpp
  src/mod/features/remap_buttons.cpp
  src/mod/features/small_patches.cpp
  src/mod/features/sounds_encounters.cpp
  src/mod/save/save.h
  src/mod/save/save_migration.cpp
  src/mod/utils/get_badges.cpp
  src/mod/utils/get_max_level.cpp
Labels: port

#1 Update PokemonParam.h
  src/mod/externals/Pml/PokePara/PokemonParam.h
Labels: bug

#40 New Poké Balls
  src/mod/data/balls.h
  src/mod/data/items.h
  src/mod/externals/Dpr/Battle/Logic/BattleViewBase.h
  src/mod/externals/Dpr/Battle/View/BtlvBallInfo.h
  src/mod/externals/Dpr/Battle/View/Systems/BTLV_WAZA_EFF_PARAM.h
  src/mod/externals/Dpr/Battle/View/Systems/BattleViewSystem.h
  src/mod/externals/Dpr/SealPreview/SealPreviewViewSystem.h
  src/mod/externals/Pml/PokePara/Accessor.h
  src/mod/externals/System/String.h
  src/mod/features/features.h
  src/mod/features/main.cpp
  src/mod/features/more_balls.cpp
  src/mod/features/unity_logging.cpp
  src/mod/ui/ui.cpp
Labels: feature
