Repository TeamLumi/Luminescent_ExLaunch, pull requests merged in 2023-09, with the labels that each got.

#61 Debug viewer + A few fixes
  src/mod/externals/Dpr/Battle/Logic/Common.h
  src/mod/externals/Dpr/Battle/Logic/EventFactor.h
  src/mod/externals/Dpr/Battle/Logic/EventVar.h
  src/mod/externals/FieldCharacterEntity.h
  src/mod/externals/FieldPlayerEntity.h
  src/mod/externals/UnityEngine/Vector2Int.h
  src/mod/externals/UnityEngine/Vector3.h
  src/mod/features/features.h
  src/mod/features/items.cpp
  src/mod/features/items/items.h
  src/mod/features/items/leek.cpp
  src/mod/features/main.cpp
  src/mod/features/more_commands.cpp
  src/mod/features/npc_collision_audio.cpp
  src/mod/ui/base/child.h
  src/mod/ui/base/collapsing_header.h
  src/mod/ui/base/element.h
  src/mod/ui/base/window.h
  src/mod/ui/components/data_viewer.h
  src/mod/ui/ui.cpp
Labels: bug, debug

#62 Can't Escape Flag
  src/mod/externals/Dpr/Battle/Logic/BATTLE_SETUP_PARAM.h
  src/mod/externals/Dpr/Battle/Logic/BtlCompetitor.h
  src/mod/externals/Dpr/Battle/Logic/BtlEscapeMode.h
  src/mod/externals/Dpr/Battle/Logic/BtlRule.h
  src/mod/externals/Dpr/Battle/Logic/MainModule.h
  src/mod/externals/Dpr/Battle/Logic/Section.h
  src/mod/externals/Dpr/Battle/Logic/Section_UseItem_Core.h
  src/mod/externals/FlagWork_Enums.h
  src/mod/features/ability_changes.cpp
  src/mod/features/battle_escape_flag.cpp
  src/mod/features/features.h
  src/mod/features/main.cpp
Labels: port

#63 Custom evolution methods
  src/mod/data/types.h
  src/mod/data/zones.h
  src/mod/externals/DPData/Form_Enums.h
  src/mod/externals/DPData/PoffinData.h
  src/mod/externals/DPData/PoffinSaveData.h
  src/mod/externals/Dpr/Battle/Logic/BATTLE_SETUP_PARAM.h
  src/mod/externals/Dpr/Battle/Logic/BTL_PARTY.h
  src/mod/externals/Dpr/Battle/Logic/BTL_POKEPARAM.h
  src/mod/externals/Dpr/Battle/Logic/BattleEnv.h
  src/mod/externals/Dpr/Battle/Logic/BattleProc.h
  src/mod/externals/Dpr/Battle/Logic/MainModule.h
  src/mod/externals/Dpr/Battle/Logic/POKECON.h
  src/mod/externals/Dpr/Battle/Logic/PokeResult.h
  src/mod/externals/Dpr/Field/Walking/FieldWalkingManager.h
  src/mod/externals/Dpr/Field/Walking/WalkingAIManager.h
  src/mod/externals/GameManager.h
  src/mod/externals/PeriodOfDay.h
  src/mod/externals/PlayerWork.h
  src/mod/externals/Pml/Personal/EvolveCond.h
  src/mod/externals/Pml/Personal/EvolveTableExtensions.h
  src/mod/externals/Pml/Personal/PersonalSystem.h
  src/mod/externals/Pml/PmlUse.h
  src/mod/externals/Pml/PokePara/Accessor.h
  src/mod/externals/Pml/PokePara/CalcTool.h
  src/mod/externals/Pml/PokePara/CoreParam.h
  src/mod/externals/Pml/PokePara/EggCheckType.h
  src/mod/externals/Pml/PokePara/EvolveManager.h
  src/mod/externals/Pml/PokePara/EvolveSituation.h
  src/mod/externals/Pml/PokePara/OwnerInfo.h
  src/mod/externals/Pml/PokeParty.h
  src/mod/externals/Pml/Sex.h
  src/mod/externals/Pml/WazaData.h
  src/mod/externals/Pml/WazaData/WazaDataSystem.h
  src/mod/externals/XLSXContent/EvolveTable.h
  src/mod/features/area_zone_codes.cpp
  src/mod/features/debug/battle_bundles_in_ui.cpp
  src/mod/features/encounter_slots.cpp
  src/mod/features/features.h
  src/mod/features/hidden_power_ui.cpp
  src/mod/features/items/ability_patch.cpp
  src/mod/features/main.cpp
  src/mod/features/more_commands.cpp
  src/mod/features/more_evolution_methods.cpp
  src/mod/ui/base/element.h
  src/mod/ui/base/window.h
  src/mod/ui/tools/misc_tool.h
  src/mod/ui/tools/poffin_tool.h
  src/mod/ui/tools/pokemon_tool.h
  src/mod/ui/ui.cpp
Labels: feature

#65 Boutique Reordering
  src/mod/data/outfits.h
  src/mod/externals/Dpr/UI/ShopBoutiqueItemItem.h
  src/mod/externals/Dpr/UI/UIManager.h
  src/mod/externals/PlayerWork.h
  src/mod/externals/XLSXContent/UIDatabase.h
  src/mod/features/features.h
  src/mod/features/gender_neutral_boutique.cpp
  src/mod/features/items/leek.cpp
  src/mod/features/main.cpp
  src/mod/features/outfit_neutral_ui.cpp
Labels: port, feature

#66 Port Poké Radar fixes
  src/mod/externals/Dpr/Field/SwayGrass.h
  src/mod/features/features.h
  src/mod/features/gender_neutral_boutique.cpp
  src/mod/features/main.cpp
  src/mod/features/poke_radar_fixes.cpp
Labels: port

#64 Battle camera transition reset fix.
  src/mod/externals/BattlePokemonEntity.h
  src/mod/externals/Dpr/Battle/Logic/BattleViewBase.h
  src/mod/externals/Dpr/Battle/View/BtlvBehaviour.h
  src/mod/externals/Dpr/Battle/View/BtlvObjectFollowInfo.h
  src/mod/externals/Dpr/Battle/View/BtlvUtility.h
  src/mod/externals/Dpr/Battle/View/Objects/BOPokemon.h
  src/mod/externals/Dpr/Battle/View/Objects/BattleObject.h
  src/mod/externals/Dpr/Battle/View/Objects/BattleViewCharacter.h
  src/mod/externals/Dpr/Battle/View/Objects/BtlvPureObject.h
  src/mod/externals/Dpr/Battle/View/Objects/BtlvSound.h
  src/mod/externals/Dpr/Battle/View/Objects/MotionTimingData.h
  src/mod/externals/Dpr/Battle/View/PokeFollowInfo.h
  src/mod/externals/Dpr/Battle/View/SimpleParam.h
  src/mod/externals/Dpr/Battle/View/Systems/BTLV_ATTR_EFF_PARAM.h
  src/mod/externals/Dpr/Battle/View/Systems/BattleCameraSystem.h
  src/mod/externals/Dpr/Battle/View/Systems/BattleCharacterSystem.h
  src/mod/externals/Dpr/Battle/View/Systems/BattleViewSystem.h
  src/mod/externals/Dpr/Battle/View/Systems/DeadActParam.h
  src/mod/externals/Dpr/Battle/View/Systems/EndGActParam.h
  src/mod/externals/Dpr/Battle/View/Systems/MemberChangeActParam.h
  src/mod/externals/Dpr/Battle/View/Systems/MemberOutActParam.h
  src/mod/externals/Dpr/Battle/View/Systems/StartGActParam.h
  src/mod/externals/Dpr/Battle/View/Systems/TrainerTalkParam.h
  src/mod/externals/Dpr/SealPreview/SealPreviewCameraSystem.h
  src/mod/externals/Dpr/SequenceEditor/SequenceCameraSystem.h
  src/mod/externals/System/Nullable.h
  src/mod/features/battle_camera_reset_fix.cpp
  src/mod/features/features.h
  src/mod/features/main.cpp
  src/mod/ui/debug_menu_hooks.cpp
Labels: feature

#67 Swam forms
  src/mod/externals/Dpr/Message/MessageGlossaryParseDataModel.h
  src/mod/externals/Dpr/Message/MessageManager.h
  src/mod/externals/GameData/DataManager.h
  src/mod/externals/Pml/Personal/SexVector.h
  src/mod/externals/TairyouHasseiPokeManager.h
  src/mod/externals/XLSXContent/PokemonInfo.h
  src/mod/externals/ZoneWork.h
  src/mod/features/features.h
  src/mod/features/main.cpp
  src/mod/features/swarm_forms.cpp
Labels: port
