Repository TeamLumi/Luminescent_ExLaunch, pull requests merged in 2024-08, with the labels that each got.

#108 Re:Lumi Dex and Script Debugger
  src/mod/data/features.h
  src/mod/externals/Dpr/Demo/Demo_Evolve.h
  src/mod/externals/Dpr/EvScript/EvDataManager.h
  src/mod/externals/Dpr/EvScript/EvScriptData.h
  src/mod/externals/Dpr/Message/MessageHelper.h
  src/mod/externals/Dpr/Message/MessageManager.h
  src/mod/externals/Dpr/UI/TypePanel.h
  src/mod/externals/Dpr/UI/UIManager.h
  src/mod/externals/Dpr/UI/UIText.h
  src/mod/externals/Dpr/UI/ZukanDescriptionPanel.h
  src/mod/externals/Dpr/UI/ZukanLanguageButton.h
  src/mod/externals/EvData.h
  src/mod/externals/EvData/Aregment.h
  src/mod/externals/EvData/ArgType.h
  src/mod/externals/EvData/Command.h
  src/mod/externals/EvData/Script.h
  src/mod/externals/EvData/_EvData.h
  src/mod/externals/FlagWork_Enums.h
  src/mod/externals/UnityEngine/Component.h
  src/mod/externals/UnityEngine/Sprite.h
  src/mod/externals/UnityEngine/Transform.h
  src/mod/externals/UnityEngine/UI/Image.h
  src/mod/externals/UnityEngine/UI/ListPool.h
  src/mod/features/commands.cpp
  src/mod/features/commands/toggle_collision_box.cpp
  src/mod/features/commands/utils/utils.cpp
  src/mod/features/commands/utils/utils.h
  src/mod/features/ev_iv_ui.cpp
  src/mod/features/features.h
  src/mod/features/main.cpp
  src/mod/features/relumi_dex_ui.cpp
  src/mod/features/small_patches.cpp
  src/mod/ui/base/element.h
  src/mod/ui/base/window.h
  src/mod/ui/components/data_viewer.h
  src/mod/ui/components/element_inspector.h
  src/mod/ui/debug_menu_hooks.cpp
  src/mod/ui/tools/misc_tool.h
  src/mod/ui/tools/save_tool.h
  src/mod/ui/tools/script_tool.h
  src/mod/ui/ui.cpp
  src/mod/ui/ui.h
Labels: feature, debug

#110 Array overhaul
  src/mod/externals/DPData/GET_STATUS.h
  src/mod/externals/DPData/KinomiGrow.h
  src/mod/externals/DPData/TR_BATTLE_DATA.h
  src/mod/externals/Dpr/Battle/Logic/Handler/Field.h
  src/mod/externals/Dpr/Battle/Logic/Handler/Side.h
  src/mod/externals/Dpr/Battle/Logic/Handler/Waza.h
  src/mod/externals/Dpr/Box/SaveBoxData.h
  src/mod/externals/Dpr/Box/SaveBoxTrayData.h
  src/mod/externals/Dpr/Item/SaveItem.h
  src/mod/externals/MonsLv.h
  src/mod/externals/Pml/MonsNo.h
  src/mod/externals/Pml/PokePara/SerializedPokemonFull.h
  src/mod/externals/Pml/WazaNo.h
  src/mod/externals/System/Primitives.h
  src/mod/externals/System/String.h
  src/mod/externals/il2cpp-api.h
  src/mod/features/encounter_slots.cpp
  src/mod/features/field_handlers.cpp
  src/mod/features/key_items/incense_burner.cpp
  src/mod/features/move_handlers.cpp
  src/mod/features/move_handlers/flame_burst.cpp
  src/mod/features/pickup.cpp
  src/mod/features/side_handlers.cpp
  src/mod/save/data/berry/berry.cpp
  src/mod/save/data/box/box.cpp
  src/mod/save/data/box/box.h
  src/mod/save/data/dex/dex.cpp
  src/mod/save/data/flag/flag.cpp
  src/mod/save/data/item/item.cpp
  src/mod/save/data/string/string.h
  src/mod/save/data/sysflag/sysflag.cpp
  src/mod/save/data/trainer/trainer.cpp
  src/mod/save/data/work/work.cpp
  src/mod/save/migration/vanilla_1.cpp
  src/mod/ui/tools/poffin_tool.h
Labels: structure

#111 Port - Local Trades Extension
  src/mod/data/features.h
  src/mod/externals/Dpr/Message/MessageManager.h
  src/mod/externals/GameData/DataManager.h
  src/mod/externals/LocalKoukan.h
  src/mod/externals/PlayerWork.h
  src/mod/externals/Pml/PokePara/Condition.h
  src/mod/externals/Pml/PokePara/CoreParam.h
  src/mod/externals/Pml/PokePara/OwnerInfo.h
  src/mod/externals/XLSXContent/LocalKoukanData.h
  src/mod/externals/poketool/poke_memo/DataType.h
  src/mod/externals/poketool/poke_memo/poketool_poke_memo.h
  src/mod/externals/poketool/pokeplace/PlaceNo.h
  src/mod/features/features.h
  src/mod/features/local_trades_extension.cpp
  src/mod/features/main.cpp
  src/mod/romdata/data/LocalTrade.h
  src/mod/romdata/local_trades.cpp
  src/mod/romdata/romdata.h
Labels: port

#113 Restore Field Waza Functionality
  src/mod/features/pla_context_menu.cpp
Labels: bug

#114 Feature: JSON-ify Feature Selection
  include/nn/fs/fs_mount.hpp
  src/mod/features/main.cpp
  src/mod/main.cpp
  src/mod/romdata/feature_status.cpp
  src/mod/romdata/romdata.h
Labels: feature

#115 Bug Fix: Hardcoded UG Shinies
  src/mod/features/shiny_rates.cpp
Labels: bug

#119 Pokémon Variants
  src/common/memory/string.cpp
  src/common/memory/string.h
  src/mod/data/features.h
  src/mod/externals/BattlePokemonEntity.h
  src/mod/externals/CustomNodeMaterial.h
  src/mod/externals/CustomNodeProperty.h
  src/mod/externals/CustomNodeVisibility.h
  src/mod/externals/DPData/Form_Enums.h
  src/mod/externals/Dpr/Contest/AContestPlayerData.h
  src/mod/externals/Dpr/Contest/ContestPlayerEntity.h
  src/mod/externals/Dpr/Contest/PokemonInfo.h
  src/mod/externals/Dpr/PatcheelPattern.h
  src/mod/externals/Dpr/UI/UIManager.h
  src/mod/externals/Dpr/UI/ZukanCompareWeightController.h
  src/mod/externals/Dpr/UI/ZukanInfo.h
  src/mod/externals/GFL.h
  src/mod/externals/MaterialParam.h
  src/mod/externals/MaterialUsing.h
  src/mod/externals/Pml/Personal/EvolveCond.h
  src/mod/externals/Pml/Personal/GrowTableExtensions.h
  src/mod/externals/Pml/Personal/PersonalSystem.h
  src/mod/externals/Pml/PokePara/Accessor.h
  src/mod/externals/Pml/PokePara/CalcTool.h
  src/mod/externals/Pml/PokePara/CoreParam.h
  src/mod/externals/Pml/PokePara/EggGenerator.h
  src/mod/externals/Pml/PokePara/EggParam.h
  src/mod/externals/Pml/PokePara/Parents.h
  src/mod/externals/Pml/PokePara/PokemonParam.h
  src/mod/externals/Pml/PokePara/RareType.h
  src/mod/externals/Pml/WazaNo.h
  src/mod/externals/PokemonCustomNodeAnim.h
  src/mod/externals/SpriteAtlasID.h
  src/mod/externals/UnityEngine/Component.h
  src/mod/externals/UnityEngine/Events/UnityAction.h
  src/mod/externals/UnityEngine/Renderer.h
  src/mod/externals/UnityEngine/Rendering/CompareFunction.h
  src/mod/externals/UnityEngine/Rendering/StencilOp.h
  src/mod/externals/UnityEngine/_Object.h
  src/mod/externals/XLSXContent/GrowTable.h
  src/mod/externals/XLSXContent/LocalKoukanData.h
  src/mod/features/features.h
  src/mod/features/form_argument_generation.cpp
  src/mod/features/form_argument_pokemon_icons.cpp
  src/mod/features/main.cpp
  src/mod/features/more_evolution_methods.cpp
  src/mod/features/pla_context_menu.cpp
  src/mod/features/relearn_tms.cpp
  src/mod/features/relumi_dex_ui.cpp
  src/mod/features/spinda_hijacking.cpp
  src/mod/features/uniform_ui.cpp
  src/mod/romdata/data/ZoneRates.h
  src/mod/romdata/romdata.h
  src/mod/romdata/zone_rates.cpp
  src/mod/ui/tools/pokemon_tool.h
Labels: feature
