Repository TeamLumi/Luminescent_ExLaunch, pull requests merged in 2024-11, with the labels that each got.

#130 Command: _GET_CAUGHT_LOCATION
  src/mod/externals/Dpr/EvScript/EvCmdID.h
  src/mod/externals/Pml/PokePara/Accessor.h
  src/mod/externals/Pml/PokePara/CoreParam.h
  src/mod/features/commands.cpp
  src/mod/features/commands/commands.h
  src/mod/features/commands/get_caught_location.cpp
Labels: improvement

#132 Commands 1248-1255
  src/mod/data/features.h
  src/mod/externals/Dpr/EvScript/EvCmdID.h
  src/mod/externals/Dpr/EvScript/EvDataManager.h
  src/mod/externals/Dpr/Message/MessageManager.h
  src/mod/externals/Dpr/Message/MessageMsgFile.h
  src/mod/externals/Dpr/Message/MessageWordSetHelper.h
  src/mod/externals/Dpr/Message/MsbtDataModel.h
  src/mod/externals/Dpr/UI/UIManager.h
  src/mod/externals/Dpr/UI/UIZukanRegister.h
  src/mod/externals/EventCamera.h
  src/mod/externals/EventCameraTable.h
  src/mod/externals/FieldCamera.h
  src/mod/externals/GameManager.h
  src/mod/externals/PlayerWork.h
  src/mod/externals/Pml/PokePara/Accessor.h
  src/mod/externals/Pml/PokePara/CoreParam.h
  src/mod/externals/System/Action.h
  src/mod/externals/System/DateTime.h
  src/mod/externals/System/Reflection/MemberInfo.h
  src/mod/externals/System/Type.h
  src/mod/externals/UnityEngine/Camera.h
  src/mod/externals/UnityEngine/JsonUtility.h
  src/mod/features/ayou_patches.cpp
  src/mod/features/commands.cpp
  src/mod/features/commands/add_pokemon_ui_extra.cpp
  src/mod/features/commands/ayou_name.cpp
  src/mod/features/commands/case_call.cpp
  src/mod/features/commands/change_formno.cpp
  src/mod/features/commands/commands.h
  src/mod/features/commands/get_caught_location.cpp
  src/mod/features/commands/get_costume_gender.cpp
  src/mod/features/commands/pokemon_name_form.cpp
  src/mod/features/commands/set_ayou_name.cpp
  src/mod/features/commands/utils/utils.cpp
  src/mod/features/commands/utils/utils.h
  src/mod/features/features.h
  src/mod/features/main.cpp
  src/mod/features/small_patches.cpp
  src/mod/save/data/ayou/ayou.cpp
  src/mod/save/data/ayou/ayou.h
  src/mod/save/migration/release.cpp
  src/mod/save/save.h
  src/mod/save/save_hooks.cpp
  src/mod/ui/tools/script_tool.h
Labels: feature, save

#133 Dialog text color & Battle UI fixes
  src/mod/data/features.h
  src/mod/data/outfits.h
  src/mod/externals/Dpr/Message/FontManager.h
  src/mod/externals/Dpr/MsgWindow/WindowMsgText.h
  src/mod/externals/Dpr/UI/CharacterModelView.h
  src/mod/externals/Dpr/UI/ModelViewBase.h
  src/mod/externals/Dpr/UI/UIModelViewController.h
  src/mod/externals/TMPro/TextMeshProUGUI.h
  src/mod/externals/UnityEngine/Component.h
  src/mod/externals/UnityEngine/UI/Image.h
  src/mod/features/battle/battle_situation.cpp
  src/mod/features/features.h
  src/mod/features/gender_neutral_boutique.cpp
  src/mod/features/main.cpp
  src/mod/features/mega_evolution.cpp
  src/mod/features/text_color.cpp
  src/mod/features/ui/madrid_battle_ui.cpp
Labels: feature, improvement
