Repository TeamLumi/Luminescent_ExLaunch, pull requests merged in 2025-02, with the labels that each got.

#157 NPC coords in Inspector
  src/mod/ui/components/element_inspector.h
Labels: debug

#161 Move Tutor UI
  src/common/memory/string.cpp
  src/common/memory/string.h
  src/mod/data/features.h
  src/mod/externals/Dpr/EvScript/EvCmdID.h
  src/mod/externals/Dpr/EvScript/EvDataManager.h
  src/mod/externals/Dpr/Message/MessageWordSetHelper.h
  src/mod/externals/Dpr/UI/PokemonSick.h
  src/mod/externals/Dpr/UI/UIManager.h
  src/mod/externals/Dpr/UI/UIMsgWindowController.h
  src/mod/externals/Dpr/UI/UIText.h
  src/mod/externals/Dpr/UI/UIWazaManage.h
  src/mod/externals/Dpr/UI/WazaManageCondition.h
  src/mod/externals/Dpr/UI/WazaManagePokemonStausPanel.h
  src/mod/externals/Dpr/UI/WazaManageWazaStatusPanel.h
  src/mod/externals/Pml/PokePara/CoreParam.h
  src/mod/externals/System/Action.h
  src/mod/externals/System/Collections/Generic/IEnumerable.h
  src/mod/externals/System/Collections/Generic/List.h
  src/mod/externals/TMPro/Extents.h
  src/mod/externals/TMPro/HighlightState.h
  src/mod/externals/TMPro/TMP_ColorGradient.h
  src/mod/externals/TMPro/TMP_FontStyleStack.h
  src/mod/externals/TMPro/TMP_Offset.h
  src/mod/externals/TMPro/TMP_Text.h
  src/mod/externals/TMPro/TMP_TextInfo.h
  src/mod/externals/TMPro/TMP_TextProcessingStack.h
  src/mod/externals/TMPro/TextMeshProUGUI.h
  src/mod/externals/UnityEngine/Color32.h
  src/mod/features/commands.cpp
  src/mod/features/commands/check_tutor_move.cpp
  src/mod/features/commands/commands.h
  src/mod/features/commands/move_tutor_ui.cpp
  src/mod/features/features.h
  src/mod/features/gender_neutral_boutique.cpp
  src/mod/features/items/repel_fix.cpp
  src/mod/features/local_trades_extension.cpp
  src/mod/features/main.cpp
  src/mod/features/more_evolution_methods.cpp
  src/mod/features/move_tutor_relearner.cpp
  src/mod/features/pla_context_menu.cpp
  src/mod/features/spinda_hijacking.cpp
  src/mod/romdata/data/MoveTutor.h
  src/mod/romdata/local_trades.cpp
  src/mod/romdata/move_tutors.cpp
  src/mod/romdata/romdata.h
Labels: feature

#164 Command: _GET_HIGHEST_RADAR_STREAK
  src/mod/externals/Dpr/EvScript/EvCmdID.h
  src/mod/externals/PlayerWork.h
  src/mod/features/commands.cpp
  src/mod/features/commands/commands.h
  src/mod/features/commands/get_highest_radar_streak.cpp
Labels: feature

#168 Platinum Veilstone Gym
  src/mod/data/features.h
  src/mod/externals/BaseEntity.h
  src/mod/externals/DIR.h
  src/mod/externals/Dpr/EvScript/EvCmdID.h
  src/mod/externals/Dpr/EvScript/EvDataManager.h
  src/mod/externals/Dpr/Field/WA_Kairiki.h
  src/mod/externals/FieldEventEntity.h
  src/mod/externals/FieldManager.h
  src/mod/externals/FieldObjectEntity.h
  src/mod/externals/FieldPlayerEntity.h
  src/mod/externals/FlagWork_Enums.h
  src/mod/externals/GameData/DataManager.h
  src/mod/externals/UnityEngine/Camera.h
  src/mod/features/commands.cpp
  src/mod/features/commands/commands.h
  src/mod/features/commands/entity_move.cpp
  src/mod/features/commands/event_entity_clip_play_by_index.cpp
  src/mod/features/commands/event_entity_clip_wait_by_index.cpp
  src/mod/features/commands/get_tile_attribute.cpp
  src/mod/features/features.h
  src/mod/features/main.cpp
  src/mod/features/pushable_entities.cpp
  src/mod/features/small_patches.cpp
  src/mod/ui/components/data_viewer.h
Labels: feature, debug
