Repository TeamLumi/Luminescent_ExLaunch, pull requests merged in 2025-09, with the labels that each got.

#191 Yet More Command Changes
  src/mod/data/balls.h
  src/mod/data/items.h
  src/mod/externals/BaseEntity.h
  src/mod/externals/Dpr/EvScript/EvCmdID.h
  src/mod/externals/Pml/PmlUse.h
  src/mod/features/commands.cpp
  src/mod/features/commands/commands.h
  src/mod/features/commands/entity_move.cpp
  src/mod/features/commands/ifcoords_call.cpp
  src/mod/features/commands/ifcoords_jump.cpp
  src/mod/features/commands/obj_dir_change.cpp
  src/mod/features/commands/utils/cmd_utils.cpp
  src/mod/features/commands/utils/cmd_utils.h
  src/mod/features/commands/wait_for_gameobject.cpp
  src/mod/ui/debug_menu_hooks.cpp
Labels: feature, debug, improvement, command

#192 Improvement: JSONify Outfit Obtention
  src/mod/features/gender_neutral_boutique.cpp
  src/mod/romdata/data/OutfitData.h
  src/mod/romdata/outfit_data.cpp
  src/mod/romdata/romdata.h
Labels: improvement

#193 Fix for Disabled moves softlock
  src/mod/externals/Dpr/Battle/Logic/BTL_ACTION.h
  src/mod/externals/Dpr/Battle/Logic/BTL_ACTION_PARAM.h
  src/mod/externals/Dpr/Battle/Logic/BTL_ACTION_PARAM_OBJ.h
  src/mod/externals/Dpr/Battle/Logic/BTL_CLIENT.h
  src/mod/externals/Dpr/Battle/Logic/BattleViewBase.h
  src/mod/externals/Dpr/Battle/Logic/SVCL_ACTION.h
  src/mod/externals/Dpr/Battle/Logic/Section_StoreActions.h
  src/mod/externals/Dpr/Battle/View/UI/BUITargetSelect.h
  src/mod/externals/Dpr/Battle/View/UI/BUIWazaList.h
  src/mod/features/ui/madrid_battle_ui.cpp
Labels: bug
